Story 52
tnodland/little_shop_v2 pull request #168
Opened 2019-04-08 18:28 UTC by tnodland

closes #62

2019-04-08 19:39 UTC, wipegup approved these changes
Looks good

2019-04-08 19:39 UTC, wipegup commented on app/controllers/merchants/orders_controller.rb
> +    @items = Item.find_by_order(@order, merchant)
Maybe `find_by_order` could be an `Order` instance method that takes the merchant as an argument?

```
@items = @order.merchants_items(merchant)
```

Where:
```
class Order < Application Record
  #Code
  def merchants_items(merchant)
    items.where(user:merchant)
  end
end
```

My thinking is that we have already "pulled" out the order information, so we might as well use that in finding the items

2019-04-08 20:41 UTC, wipegup requested changes
I will be making changes on the factories to un-break some tests

2019-04-08 20:48 UTC, wipegup approved these changes

2019-04-09 00:53 UTC, whois-jon-peterson approved these changes

2019-04-09 15:46 UTC, Vjp888 approved these changes

2019-04-09 15:48 UTC, merged